//! Network-silent command-line adapter for Heimdall's decompiler and disassembler.

use std::{fs, io::Read, path::PathBuf, process::ExitCode, str::FromStr};

use clap::{Parser, ValueEnum};
use eyre::{bail, Context, Result};
use heimdall_decompiler::{decompile, DecompilerArgs, DecompilerArgsBuilder, HardFork};
use heimdall_disassembler::{disassemble, DisassemblerArgsBuilder};
use serde::Serialize;

const HEIMDALL_REVISION: &str = env!("HEIMDALL_GIT_REVISION");

#[derive(Debug, Clone, Copy, ValueEnum)]
enum SourceFormat {
    Solidity,
    Yul,
}

#[derive(Debug, Parser)]
#[command(
    about = "Decompile 0x-prefixed EVM bytecode locally with heimdall-rs",
    long_about = None
)]
struct Args {
    /// One 0x-prefixed EVM bytecode blob.
    #[arg(long, conflicts_with_all = ["file", "stdin"])]
    bytecode: Option<String>,

    /// Read one 0x-prefixed EVM bytecode blob from a UTF-8 file.
    #[arg(long, value_name = "PATH", conflicts_with_all = ["bytecode", "stdin"])]
    file: Option<PathBuf>,

    /// Read one 0x-prefixed EVM bytecode blob from standard input.
    #[arg(long, conflicts_with_all = ["bytecode", "file"])]
    stdin: bool,

    /// Source representation generated by Heimdall.
    #[arg(long, value_enum, default_value_t = SourceFormat::Solidity)]
    source: SourceFormat,

    /// Per-function symbolic-execution timeout in milliseconds.
    #[arg(long, default_value_t = 10_000)]
    timeout: u64,

    /// Fixed hardfork used for opcode recognition. 'auto' is rejected offline.
    #[arg(long, default_value = "latest")]
    hardfork: String,
}

#[derive(Debug, Serialize)]
struct Output {
    engine: &'static str,
    engine_version: &'static str,
    engine_revision: &'static str,
    requested_hardfork: String,
    effective_hardfork: String,
    source_format: &'static str,
    supplied_input_bytes: usize,
    analyzed_bytes: usize,
    source: Option<String>,
    abi: serde_json::Value,
    abi_with_details: serde_json::Value,
    disassembly: String,
}

fn read_input(args: &Args) -> Result<String> {
    let selected = usize::from(args.bytecode.is_some())
        + usize::from(args.file.is_some())
        + usize::from(args.stdin);
    if selected != 1 {
        bail!("select exactly one input: --bytecode, --file, or --stdin");
    }

    if let Some(value) = &args.bytecode {
        return Ok(value.clone());
    }
    if let Some(path) = &args.file {
        return fs::read_to_string(path)
            .wrap_err_with(|| format!("failed to read bytecode file '{}'", path.display()));
    }

    let mut value = String::new();
    std::io::stdin().read_to_string(&mut value).wrap_err("failed to read standard input")?;
    Ok(value)
}

fn normalize_bytecode(raw: &str) -> Result<String> {
    let value = raw.trim();
    if !value.starts_with("0x") {
        bail!("bytecode must begin with lowercase '0x'");
    }

    let hex = &value[2..];
    if hex.is_empty() {
        bail!("bytecode is empty");
    }
    if hex.len() % 2 != 0 {
        bail!("bytecode must contain an even number of hexadecimal digits");
    }
    if !hex.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        bail!("bytecode contains a non-hexadecimal character");
    }

    let mut bytes = (0..hex.len())
        .step_by(2)
        .map(|offset| u8::from_str_radix(&hex[offset..offset + 2], 16))
        .collect::<Result<Vec<_>, _>>()?;
    pad_truncated_push(&mut bytes);
    Ok(format!("0x{}", encode_hex(&bytes)))
}

fn pad_truncated_push(bytes: &mut Vec<u8>) {
    let mut pc = 0;
    while pc < bytes.len() {
        let width = match bytes[pc] {
            opcode @ 0x60..=0x7f => usize::from(opcode - 0x5f),
            _ => 0,
        };
        let available = bytes.len() - pc - 1;
        if width > available {
            bytes.resize(bytes.len() + width - available, 0);
        }
        pc += 1 + width;
    }
}

fn encode_hex(bytes: &[u8]) -> String {
    use std::fmt::Write as _;

    bytes.iter().fold(String::new(), |mut encoded, byte| {
        write!(encoded, "{byte:02x}").expect("writing to a string cannot fail");
        encoded
    })
}

fn build_decompiler_args(
    target: String,
    hardfork: HardFork,
    source: SourceFormat,
    timeout: u64,
) -> Result<DecompilerArgs> {
    let include_solidity = matches!(source, SourceFormat::Solidity);
    DecompilerArgsBuilder::new()
        .target(target)
        .rpc_url(String::new())
        .skip_resolving(true)
        .include_solidity(include_solidity)
        .include_yul(!include_solidity)
        .timeout(timeout)
        .llm_postprocess(false)
        .openrouter_api_key(String::new())
        .model(String::new())
        .etherscan_api_key(String::new())
        .hardfork(hardfork)
        .build()
        .wrap_err("failed to construct Heimdall decompiler arguments")
}

async fn run() -> Result<()> {
    let args = Args::parse();
    let supplied = read_input(&args)?;
    let supplied_input_bytes = supplied.trim().strip_prefix("0x").map_or(0, |hex| hex.len() / 2);
    let target = normalize_bytecode(&supplied)?;
    let hardfork = HardFork::from_str(&args.hardfork).map_err(eyre::Report::msg)?;
    if hardfork == HardFork::Auto {
        bail!("hardfork 'auto' requires chain data and is disabled offline");
    }

    let include_solidity = matches!(args.source, SourceFormat::Solidity);
    let decompiler_args =
        build_decompiler_args(target.clone(), hardfork, args.source, args.timeout)?;

    let result = decompile(decompiler_args).await.wrap_err("Heimdall decompilation failed")?;
    let disassembly = disassemble(
        DisassemblerArgsBuilder::new()
            .target(target.clone())
            .rpc_url(String::new())
            .hardfork(hardfork)
            .build()
            .wrap_err("failed to construct Heimdall disassembler arguments")?,
    )
    .await
    .wrap_err("Heimdall disassembly failed")?;

    let output = Output {
        engine: "heimdall-rs",
        engine_version: env!("CARGO_PKG_VERSION"),
        engine_revision: HEIMDALL_REVISION,
        requested_hardfork: hardfork.to_string(),
        effective_hardfork: hardfork.effective().to_string(),
        source_format: if include_solidity { "solidity" } else { "yul" },
        supplied_input_bytes,
        analyzed_bytes: (target.len() - 2) / 2,
        source: result.source,
        abi: serde_json::to_value(result.abi).wrap_err("failed to serialize Heimdall ABI")?,
        abi_with_details: result.abi_with_details,
        disassembly,
    };

    println!("{}", serde_json::to_string_pretty(&output)?);
    Ok(())
}

#[tokio::main]
async fn main() -> ExitCode {
    match run().await {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("error: {error:#}");
            ExitCode::FAILURE
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{build_decompiler_args, normalize_bytecode, HardFork, SourceFormat};

    #[test]
    fn accepts_prefixed_bytecode() {
        assert_eq!(normalize_bytecode("  0x60AA  ").unwrap(), "0x60aa");
    }

    #[test]
    fn rejects_unprefixed_bytecode() {
        assert!(normalize_bytecode("60aa").is_err());
    }

    #[test]
    fn rejects_empty_odd_and_non_hex_bytecode() {
        assert!(normalize_bytecode("0x").is_err());
        assert!(normalize_bytecode("0x0").is_err());
        assert!(normalize_bytecode("0xzz").is_err());
    }

    #[test]
    fn pads_truncated_push_immediates_with_zeroes() {
        assert_eq!(normalize_bytecode("0x60").unwrap(), "0x6000");
        assert_eq!(normalize_bytecode("0x0061aa").unwrap(), "0x0061aa00");
    }

    #[test]
    fn decompiler_arguments_disable_every_network_path() {
        let args = build_decompiler_args(
            "0x6000".to_string(),
            HardFork::Latest,
            SourceFormat::Solidity,
            10_000,
        )
        .unwrap();

        assert!(args.rpc_url.is_empty());
        assert!(args.etherscan_api_key.is_empty());
        assert!(args.openrouter_api_key.is_empty());
        assert!(args.skip_resolving);
        assert!(!args.llm_postprocess);
        assert_ne!(args.hardfork, HardFork::Auto);
    }
}
